apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neo4j-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: neo4j-operator-manager-role
subjects:
- kind: ServiceAccount
  name: neo4j-operator-controller-manager
