apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert # this name should match the one in certificate.yaml
  namespace: neo4j-operator-system
spec:
  dnsNames:
  - webhook-service.neo4j-operator-system.svc
  - webhook-service.neo4j-operator-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: neo4j-operator-selfsigned-issuer
  secretName: webhook-server-cert # this should match the one in manager_webhook_patch.yaml
